# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9355c67156e8b3c4ca27593afb54ff21f3e4654ee23a98bea7f6feef8b3035151c85be6e9ef171c9e3251ad3c3202ae08dca82ddce13eea75df600550db3401c

test:
  secret_key_base: 2652cdb01b7ae23a0ee7d33480961788971fde14db8544174246d718a2f67c94bd9a04f630ca7548020ff30a4eddf89d1796d20cd4f9360e87ec93e4d0258174

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
